A = int(input('Введите точку А: '))
B = int(input('Введите точку B: '))
C = int(input('Введите точку C: '))
print('Длинна отрезка AC: ' + str(C - A))
print('Длинна отрезка BC: ' + str(C - B))
print('Сумма отрезков: ' + str((C - A) + (C - B)))